export const createSupplierDTO = (data) => ({
    name: data.name?.trim(),
    company_name: data.company_name?.trim() ?? null,
    tax_id: data.tax_id?.trim().toUpperCase(),
    email: data.email?.trim().toLowerCase() ?? null,
    phone: data.phone?.trim() ?? null,
    address: data.address?.trim() ?? null,
    postal_code: data.postal_code?.trim() ?? null,
    city: data.city?.trim() ?? null,
    province: data.province?.trim() ?? null,
    country: data.country?.trim() ?? null,
    contact_person: data.contact_person?.trim() ?? null,
    payment_terms: data.payment_terms ?? null,
    bank_account: data.bank_account?.trim() ?? null,
    notes: data.notes?.trim() ?? null,
    active: data.active ?? true,
});

export const updateSupplierDTO = (data) => ({
    name: data.name?.trim(),
    company_name: data.company_name?.trim() ?? null,
    tax_id: data.tax_id?.trim().toUpperCase(),
    email: data.email?.trim().toLowerCase() ?? null,
    phone: data.phone?.trim() ?? null,
    address: data.address?.trim() ?? null,
    postal_code: data.postal_code?.trim() ?? null,
    city: data.city?.trim() ?? null,
    province: data.province?.trim() ?? null,
    country: data.country?.trim() ?? null,
    contact_person: data.contact_person?.trim() ?? null,
    payment_terms: data.payment_terms ?? null,
    bank_account: data.bank_account?.trim() ?? null,
    notes: data.notes?.trim() ?? null,
    active: data.active,
});
